server:
  port: 8088
spring:
  application:
    name: RtInfoCollectService



kafka:
    consumer:
      servers: spark1:9092,spark2:9092,spark3:9092
      enable-auto-commit: true
      auto-offset-reset: latest
      auto.commit.interval: 100
      session.timeout: 6000
      group.id: test
      topic: test
      concurrency: 10
    producer:
      bootstrap-servers: spark1:9092,spark2:9092,spark3:9092
      retries: 0
      batch-size: 4096
      buffer-memory: 40960



